---
driver:
  name: docker
  privileged: true

platforms:
- name: centos-6.6
- name: ubuntu-12.04
  run_list:
    - recipe[ubuntu]
  driver:
    image: ubuntu-upstart:12.04
    platform: ubuntu
    disable_upstart: false
    run_command: /sbin/init
